version: '3'

services:
  express-api:
    build: .
    command: npm run start
    restart: unless-stopped
    depends_on:
      - express-mongo
    ports:
      - "1337:1337"
    environment:
      - PORT=1337
      - HOST=localhost
      - MONGODB_URI=mongodb://express-mongo:27017/mongodb-rest-api
      - SALT_WORK_FACTOR=10
      - ACCESS_TOKEN_TTL=10m
      - REFRESH_TOKEN_TTL=3600
      - PRIVATE_KEY=secretKey

  express-mongo:
    image: mongo:latest
    volumes:
      - express-mongodb:/data/db

volumes:
  express-mongodb:
